name: Documentation
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocstrings mkdocs-material 
      - run: mkdocs gh-deploy --force

      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.INSTALLATION_ID }}
      
      - name: Trigger project repo workflows
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          # List of repositories to trigger
          repos=("large-language-models" "packaging-publishing" "ai-core-concepts")
          
          for repo in "${repos[@]}"; do
            curl -X POST \
              -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/acceleratescience/$repo/dispatches \
              -d '{"event_type": "rebuild_docs"}'
          done
